# docker-compose.yml
# version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mytheresa
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d # Load SQL on startup
    networks:
      - product-network
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    networks:
      - product-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  product-service:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/mytheresa?sslmode=disable
      REDIS_URL: redis:6379
    ports:
      - "4500:4500"
    networks:
      - product-network

volumes:
  pgdata:

networks:
  product-network:
